language: ruby
rvm:
  - 2.3.0

addons:
  firefox: "56.0"

before_script:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
- tar -xvzf geckodriver*
- chmod +x geckodriver
- sudo mv geckodriver /usr/local/bin/

script:
  - cucumber
